### ISSUE TITLE
Build script not working out of the box

### ISSUE THREAD

**Issue by mrksbrg** [reqT/reqT#2]
Could not build reqT on my Win7 SP1 machine.

C:\Users\Markus Borg\Documents\GitHub\reqT>build.cmd
Clean compile, removing directory target\reqT
The system cannot find the file specified.
Compiling reqT ...  21:27:53,37
scalac error: bad option: '-feature'
  scalac -help  gives more information
Error level: 1

**Comment by bjornregnell** [comment]
Which version of the scala compiler are you running?

**Comment by mrksbrg** [comment]
My version was old... Installing the latest.

**Comment by bjornregnell** [comment]
Yes, you need scala 2.10.x
