### ISSUE TITLE
Some examples are broken

### ISSUE THREAD

**Issue by srenatus** [reqT/reqT#4]
Hi there.

I suppose with the 3.0 rewrite and the `examples/` files that are older than that, it's not surprising that they don't work anymore...

In particular, I was trying to use `(m / Feature).entities` as in [model-1.scala](https://github.com/reqT/reqT/blob/3.0.x/examples/model-1.scala#L45). It seems to be `m.entitiesOfType(Feature)` now, right?

Thanks
Stephan

**Comment by bjornregnell** [comment]
Yes, thanks for this. And sorry for the delay in my response. I'll do an overhaul of the examples in the coming period. Or, you are also welcome to make a pull request!
Thanks again
Bjorn

**Comment by bjornregnell** [comment]
Actually, in version 3 the restrict operator is now \* (instead of slash) and the diff operator is now -- (instead of a single minus) so you can write expressions like this: 
`(m * Feature).entities` 
and 
`m -- (m * Feature * Status(DROPPED))` 
Hope this helped?

**Comment by bjornregnell** [comment]
I have moved the outdated examples to the old dir. In the future, I hope some more examples can materialize. In the course home page there are more examples avaliable in the reqT tutorial lecture: http://cs.lth.se/ets170/reqt/
