### ISSUE TITLE
Implement better support for integration

### ISSUE THREAD

**Issue by coroiu** [reqT/reqT#5]
To automate reqT a command like the following has to be used: 

`echo 'm.toGraph.save("graph.dot")\n:quit' | reqt -i test.model; dot -Tpdf graph.dot -o graph.pdf`

However if the file test.model contains errors reqT will just throw the error to the console and then continue on with running the Scala REPL.

**Comment by bjornregnell** [comment]
Thanks for your suggestion Andreas! I'll see what I can do about this. How would you like it to work instead? (The scala script running facilities are a bit limited, e.g. scala scripts cannot invoke other scala scripts etc.)

**Comment by coroiu** [comment]
Maybe choose a file to run and after the script is done reqT should exist with a status code (0 if no errors, -1 if exception occured etc...). Just think of how you would have wanted it to work if you wanted to make a quick php (or other) script that automatically compiles all the output files (pdf, latex, etc...). As it is now there is no direct way to check if reqT succeeded in running the script.

**Comment by bjornregnell** [comment]
I've looked into the code and both my classes FileRunner and CodeRunner interprets the code "quietly" meaning that they silently ignore error. I'm hesitant to break existing code by changing the semantics of the -i (and -t arguments), so I'm thinking of adding for instance a -ie argument that does System.exit(1) if the interpretation results in error. Would that be ok for you? 
BTW: The code is available here:
https://github.com/reqT/reqT/blob/3.0.x/src/reqT/ReadEvaluatePrintLoop.scala#L89
and called from here:
https://github.com/reqT/reqT/blob/3.0.x/src/reqT/Main.scala#L60
via the repl object here and the method interpretFile:
https://github.com/reqT/reqT/blob/3.0.x/src/reqT/ReadEvaluatePrintLoop.scala#L130

**Comment by coroiu** [comment]
After experimentig a bit with reqT I've come to the conclusion that extending reqT this way is more appropriately accomplished using external scripts! Closing issue, thanks for the help :)

**Comment by bjornregnell** [comment]
Thanks for your input! It would be nice to see some examples of how you solved your issue with swallowed compile errors using external scripts. Could you perhaps send me some examples?
