### ISSUE TITLE
Flag -t and -i does not support reading files with special characters

### ISSUE THREAD

**Issue by coroiu** [reqT/reqT#6]
When trying to read and evaluate a file of scala code containing the characters "å, ä, ö" causes reqT to fail with the following exception.

```
** Test model files:  ETS170/test.model
<console>:1: error: ';' expected but '.' found.
      {result(0) = {ERROR java.nio.charset.MalformedInputException: Input length = 1}: reqT.Model}
                              ^
java.lang.Error: INTERPRETATION ERROR! script must evaluate to valid reqT.Model
  at $anonfun$1$$anonfun$apply$1.apply(<console>:18)
  at $anonfun$1$$anonfun$apply$1.apply(<console>:18)
  at scala.Option.getOrElse(Option.scala:121)
  at $anonfun$1.apply(<console>:18)
  at $anonfun$1.apply(<console>:17)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.Iterator$class.foreach(Iterator.scala:750)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  ... 35 elided
```

Note that I've tried saving the file using different encodings including: UTF-8, UTF-8 with BOM and ISO 8859-1. Neither resulted in anything than the above mentioned exception. _Removing_ the special characters solved the problem.
## Possible workaround

Use the built in command `:paste` and pipe in the contents of the file instead. Or just remove the characters and write in english.

**Comment by bjornregnell** [comment]
Thanks for identifying this problem! I'm trying to replicate this on Linux and Windows but it seems to work with ÅÄÖåäö for me using UTF-8 on Linux Mint 13 Xfce, as well as with Western International (code page 1252) on Windows 7. What box are you running on? MacOSX? Can you pls email me the test.model file and the code you are running with -i command so I can replicate this? -> bjorn.regnell at cs.lth.se.

**Comment by coroiu** [comment]
Might be my environment running Ubuntu 12.04. I will try to look into it a bit more and see if I can't replicate it on another device.

**Comment by bjornregnell** [comment]
The -i and -t options delegate the file-loading to reqT.load("filename") which is available here:
https://github.com/reqT/reqT/blob/3.0.x/src/reqT/Utils.scala#L154 
It loads a string. Is it the case that your test.model file is serialized to a binary? Or is it a text file with scala code describing a model?
If not, I guess your file is not loadable from the reqT prompt with load either? What does this output on your box:
reqT> load("test.model")

**Comment by coroiu** [comment]
It's just scala code in a txt file. I have no idea why it won't work though, tried on my home Ubuntu 14.04 and it works without any issues. Even tried installing Oracle JDK7 on my server but it still gives me that weird error.

```
reqT> reqT.load("test2.model")
res0: String = ERROR java.nio.charset.MalformedInputException: Input length = 1
```

**Comment by bjornregnell** [comment]
I guess this is about old versions of jline or something. I'm closing this for now, and we can reopen if it is possible to replicate on a new distro with up to date lib version.
