### ISSUE TITLE
fix swing gui for high-dpi screens

### ISSUE THREAD

**Issue by bjornregnell** [reqT/reqT#8]
* Prio 1: Add menu choice in menu View to change size of fonts in menu and tree view
* Prio 2: Detect screen size on start-up and set default font sizes for editor, menus and tree view

**Comment by bjornregnell** [comment]
@eHammarstrom if you feel inclined to do a quick-and-dirty fix on this, as the old swing gui will look bad on students high-dpi laptop screens, it would be nice...

**Comment by bjornregnell** [comment]
Code for inspiration in the Kojo code base where a similar fix was made:
https://bitbucket.org/lalit_pant/kojo-g/commits/edd2f210e24b4d8f4bfca0d41903aaaf34d41756
I guess stackoverflow can help if searching for stuff related to:

    val defaults = UIManager.getLookAndFeelDefaults
    val defaultFontSize = defaults.get("defaultFont").asInstanceOf[FontUIResource].getSize

**Comment by eHammarstrom** [comment]
Something like this seems to work for Prio 1:

1. Iterate through fonts
2. Update their size, but keep styling
3. Update frame

```scala
    def setGlobalSwingFontSize(size: Int): Unit = {
      import collection.JavaConverters._

      val enumKeys: Iterator[Object] =
        UIManager.getLookAndFeelDefaults.keys.asScala

      enumKeys
        .map(x => (x, UIManager.get(x))) // k => (k, v)
        .filter(_._2.isInstanceOf[FontUIResource])
        .map({ case (k, v) => (k, v.asInstanceOf[FontUIResource]) })
        .foreach({ case (k, v) =>
          UIManager.put(k, new FontUIResource(v.getFamily, v.getStyle, size))
        })

      val ff = frame.getFont

      frame.setFont(new Font(ff.getFamily, ff.getStyle, size))

      setEditorFont(editor.getFont.getSize) // handle override of editor font size

      SwingUtilities.updateComponentTreeUI(frame)
    }
```

Result (editor font max, increased global font size using View tab in menu):
![test](https://i.imgur.com/EUdP5FW.png)

I will look into dpi detection during the weekend, [it seems like we're getting support in JRE/JDK 9](http://openjdk.java.net/jeps/263)

**Comment by bjornregnell** [comment]
cool! Seems like a nice and Scala-idiomatic way of grabbing java stuff! So just go ahead with a PR when you feel ready. BTW: It should be possible to skip `.map({ case .. })` in partial functions and just use `.map{ case ... }`   etcetera, to make it easier to parse for humans :)

**Comment by eHammarstrom** [comment]
[Scaling by screen width](https://github.com/eHammarstrom/reqT/commit/a1344f065d6f73fcfc0877d9d886df5cd5886939) (as Kojo does) works, tested on a 4k resolution. And it currently scales the menu and tree view.

However, when I tried adding the `fontDeltaByScreenWidth` to `Settings.gui.fontSize` on [line 991](https://github.com/eHammarstrom/reqT/blob/3.0.x/src/reqT/gui.scala#L991) it had no effect on the editor font size.
